# Generated by Django 5.0.6 on 2024-11-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='rotulo_fecha',
            field=models.BooleanField(default=False),
        ),
    ]
