# Generated by Django 5.0.6 on 2024-11-07 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_productoa_productob_productoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.productoa'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.productob'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='producto_terminado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.productoc'),
        ),
    ]
