# Generated by Django 5.0.6 on 2024-11-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_alter_tareas_linea_alter_tareas_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='linea',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='producto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='producto_terminado',
            field=models.CharField(max_length=255, verbose_name='producto terminado'),
        ),
    ]
